# Generated by Django 4.2 on 2023-06-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_cracha_delete_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracha',
            name='rg',
            field=models.CharField(max_length=150),
        ),
    ]
