# Generated by Django 4.2 on 2023-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_cracha_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracha',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
