# Generated by Django 4.2 on 2025-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_cracha_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracha',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'SOLICITADO'), ('EM_PRODUCAO', 'EM PRODUÇÃO'), ('PENDENTE', 'PENDENTE'), ('CONFECCIONADO', 'CONFECCIONADO')], default='', max_length=100),
        ),
    ]
