# Generated by Django 5.2.6 on 2025-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_cracha_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracha',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
